- name: NFS Server playbook 
  hosts: nfs-servers 
  become: true 
  tasks: 
    - name: Update APT packages 
      apt: 
        update_cache: true 
    - name: Install common packages 
      apt: 
        name: 
          - fish 
          - tree 
        state: present 
    - name: Install nfs server package 
      apt: 
        name: nfs-kernel-server 
        state: present 
    