[all:vars]
ansible_user=kk
ansible_python_interpreter=/usr/bin/python3


[localhost]
node1 ansible_connection=local 



[agents]
node2 ansible_host=136.85.3.154  ansible_user=kk

[all:children]
localhost
agents

; ansible -i inventory.ini -m ping node1 
; ansible -i inventory.ini -m ping all 
; ansible -i inventory.ini -m command -a "uptime" all 
; ansible -i inventory.ini -m apt -a "name=nginx state=present" node2 -b